# Generated by Django 5.1.1 on 2024-09-26 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(db_index=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(db_index=True, default='Уровень не определен', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, default='+996', max_length=14, null=True),
        ),
    ]
