# Generated by Django 5.1.1 on 2024-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Введите название книг')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загружите фото книги')),
                ('description', models.TextField(verbose_name='Введите информацию коротко о книге')),
                ('url_book', models.URLField(verbose_name='Введите ссылку на сайт с полным информацией о книге')),
                ('price', models.IntegerField(verbose_name='Введите цену на книгу')),
                ('email', models.EmailField(max_length=254, verbose_name='Введите Имейл для адресс книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
