# Generated by Django 5.1.1 on 2024-09-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Роман', 'Роман'), ('Триллер', 'Триллер'), ('Детектив', 'Детектив')], max_length=120, null=True),
        ),
    ]
