# Generated by Django 5.1.1 on 2024-09-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_the_book',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='Введите сумму скидки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Роман', 'Роман'), ('Триллер', 'Триллер'), ('Детектив', 'Детектив')], max_length=120, null=True, verbose_name='Введите имя автора книги'),
        ),
    ]
