# Generated by Django 5.1.1 on 2024-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='tags',
            field=models.ManyToManyField(db_index=True, null=True, to='shop.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
